### PR TITLE
Add better support for route config

### PR DESCRIPTION
**Pull request by ddedic**

### CODE REVIEW

**Comment by jeremytubbs** [comment]
Actually I want to revoke my approval... I think I would solve this by adding a flag to the config to use package routes. This seams to be a pretty common pattern that allows the developer to define their own routes if they are have special requirements.

**Comment by spawnia** [comment]
Looks good, thanks!

**Comment by jeremytubbs** [comment]
@spawnia you should update the `README.md` to make users aware that they need to add `GRAPHQL_PLAYGROUND_DOMAIN` to the `.env`

**Comment by spawnia** [comment]
Is it necessary to have?

**Comment by jeremytubbs** [comment]
It is in the config - https://github.com/mll-lab/laravel-graphql-playground/blob/master/config/graphql-playground.php#L32

**Comment by jeremytubbs** [comment]
I don't think it is necessary... it could be blank and commented out like the previous config domain. Just thought you might have missed this.

**Comment by spawnia** [comment]
Yes, but it does have a default. I would rather not duplicate the info in the README, as i think it is fine to see it in the config.

**Comment by spawnia** [comment]
As long as it works out of the box, it should be fine.

**Pull request merged**
